# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-16 20:26
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('aww', '0005_newsletterrecipients'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=tinymce.models.HTMLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
